### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by CoderBoyo** [rockyhawk64/CommandPanels#134]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
No

### Describe the bug
The api isn't working
Error
[Server thread/ERROR]: Could not pass event PlayerInteractEvent to MegaSurvival v1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:494) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:461) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:457) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1974) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.PacketPlayInArmAnimation.a(SourceFile:31) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.PacketPlayInArmAnimation.a(SourceFile:9) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassCastException: Cannot cast net.ultibuild.main.Main to me.rockyhawk.commandpanels.CommandPanels
        at java.lang.Class.cast(Class.java:3818) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.getPlugin(JavaPlugin.java:397) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        at me.rockyhawk.commandpanels.CommandPanels.getAPI(CommandPanels.java:253) ~[?:?]
        at net.ultibuild.main.Main.OnAction(Main.java:96) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor105.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
        ... 21 more
Line 96:
CommandPanelsAPI api = CommandPanels.getAPI();

### Expected behavior
I mean there aren't supposed to be errors..

### Versions:
 - Minecraft: [e.g. 1.16]
 - CommandPanels: [Latest]

**Comment by rockyhawk64** [comment]
Check you have setup your code correct, or provide more information. Running that line works fine for me.
