### ISSUE TITLE
Purpur Support

### ISSUE THREAD

**Issue by tiredy** [rockyhawk64/CommandPanels#185]
I had an issue with panels not working correctly and when i asked about it in discord i was told the issue is purpur 
so im here asking for purpur support
here's the error if you need it 
`[11:21:47 ERROR]: Could not pass event CommandTagEvent to CommandPanels v3.17.2.2
java.lang.NullPointerException: Cannot invoke "me.rockyhawk.commandpanels.api.Panel.getConfig()" because "panel" is null
        at me.rockyhawk.commandpanels.openpanelsmanager.OpenPanelsLoader.panelCloseCommands(OpenPanelsLoader.java:115) ~[CommandPanels (1).jar:?]
        at me.rockyhawk.commandpanels.openpanelsmanager.OpenPanelsLoader.closePanelForLoader(OpenPanelsLoader.java:83) ~[CommandPanels (1).jar:?]
        at me.rockyhawk.commandpanels.classresources.ExecuteOpenVoids.openCommandPanel(ExecuteOpenVoids.java:110) ~[CommandPanels (1).jar:?]
        at me.rockyhawk.commandpanels.api.Panel.open(Panel.java:111) ~[CommandPanels (1).jar:?]
        at me.rockyhawk.commandpanels.commandtags.tags.other.SpecialTags.commandTag(SpecialTags.java:56) ~[CommandPanels (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor195.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1448]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at me.rockyhawk.commandpanels.commandtags.CommandTags.runCommand(CommandTags.java:67) ~[CommandPanels (1).jar:?]
        at me.rockyhawk.commandpanels.commandtags.CommandTags.runCommands(CommandTags.java:48) ~[CommandPanels (1).jar:?]
        at me.rockyhawk.commandpanels.Utils.onPanelClick(Utils.java:146) ~[CommandPanels (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor173.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1448]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2901) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1448]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1437) ~[purpur-1.18.1.jar:git-Purpur-1448]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1448]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1415) ~[purpur-1.18.1.jar:git-Purpur-1448]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1408) ~[purpur-1.18.1.jar:git-Purpur-1448]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1542) ~[purpur-1.18.1.jar:git-Purpur-1448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[purpur-1.18.1.jar:git-Purpur-1448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by tiredy** [comment]
they told me to change to paper in the discord as its a issue with purpur i changed to paper, still same problem just with paper
