### ISSUE TITLE
Placeholder `cp-player-online-N-visible` does not work

### ISSUE THREAD

**Issue by RobinRMC** [rockyhawk64/CommandPanels#249]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [ ] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a GitHub issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.18.2

### What Command Panels version are you using?

3.18.6.0

### What server software are you running?

Paper

### What happened?

Nothing.

### Steps to reproduce the issue

1. Put `%cp-player-online-1-visible%` somewhere in your panel, outside your panel, it doesn't matter. Just put it somewhere.
2. Trigger the action that should show the value.
3. Observe that absolutely nothing happens.

### Expected behavior

"This will ignore players that are vanished by checking for the vanished metadata."

https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/placeholders-and-panel-editing

### Error

```shell
java.lang.NumberFormatException: For input string: "1-visible"
       at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
       at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
       at java.base/java.lang.Double.parseDouble(Double.java:651)
       at Command Panels 3.18.5.1.jar//me.rockyhawk.commandpanels.classresources.placeholders.Placeholders.cpPlaceholders(Placeholders.java:337)
       at Command Panels 3.18.5.1.jar//me.rockyhawk.commandpanels.classresources.placeholders.Placeholders.setPlaceholders(Placeholders.java:37)
       at Command Panels 3.18.5.1.jar//me.rockyhawk.commandpanels.classresources.placeholders.CreateText.attachPlaceholders(CreateText.java:122)
```

### Other files

After a quick peek in the code, I noticed that Command Panels looks for `online-players-visible`, but when it actually gets activated, it looks for a placeholder ending with `-visible`.

I'm not a programmer, but it looks to me something goes wrong there.

Extra:

The configuration file tab on the wiki mentions the placeholder `cp-player-online-1-find`. This placeholder doesn't seem to exist.

```yaml
#Name that is shown when the player is offline when using %cp-player-online-1-find%
offline: Offline

#Head value that is shown when the player is offline when using %cp-player-online-1-find%
offlineHeadValue: eyJ0ZXh0d...
```

**Comment by RobinRMC** [comment]
I can confirm the issue has been resolved.

Thanks @rockyhawk64! ❤️
