### ISSUE TITLE
Error on disconnect with unclosable open

### ISSUE THREAD

**Issue by TinyTank800** [rockyhawk64/CommandPanels#287]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

latest

### What server software are you running?

Purpur

### What happened?

Error is posted on disconnect while having unclosable panel open. Reported by @ciliopiola

### Steps to reproduce the issue

Create panel with unclosable enabled
leave server
error inside console

### Expected behavior

No error

### Error (optional)

```shell
[01:16:39 INFO]: Estailuuus lost connection: Disconnected
[01:16:39 INFO]: [ClothesPlus] Setting Estailuuus back to ADVENTURE
[01:16:39 WARN]: [CommandPanels] Task #3049452 for CommandPanels v3.19.1.7 generated an exception
java.lang.NullPointerException: Cannot assign field "isOpen" because the return value of "me.rockyhawk.commandpanels.openpanelsmanager.OpenPanelsLoader.getOpenPanel(String, me.rockyhawk.commandpanels.openpanelsmanager.PanelPosition)" is null
        at me.rockyhawk.commandpanels.openpanelsmanager.UtilsPanelsLoader$1.run(UtilsPanelsLoader.java:59) ~[CommandPanels.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Other files, you can drag and drop them here to upload. (optional)

https://discord.com/channels/602338405883314206/749407995036696656/1195537408545009715
Message link

**Comment by TinyTank800** [comment]
Fix has been made and will be making a pull request when more changes are finished.
