### ISSUE TITLE
Could not pass event InventoryClientEvent

### ISSUE THREAD

**Issue by mcdaddytalk** [rockyhawk64/CommandPanels#6]
Paper 1.16.1 build 68
CommandPanels 3.2.0 (also see it in 3.1.4)

Reproduction steps:
1. /cpg # (any number)
2. attempt to add items to panel

I was thinking this had to do with chatcolors so I removed the "&8" from the beginning of the title in the "panel-1" yml
and received same error after reloading panel

`[11:19:56] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CommandPanels v3.2.0
java.lang.IllegalArgumentException: Cannot translate null text
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.1.jar:git-Paper-68]
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[patched_1.16.1.jar:git-Paper-68]
	at me.rockyhawk.commandPanels.utils.onPanelClick(utils.java:97) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor167.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-68]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-68]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-68]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2421) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-68]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by fireFerry** [comment]
Hi, this is probably a color code issue the developer needs to fix. Can you please send us the panel in question?

**Comment by mcdaddytalk** [comment]
@fireFerry thank you for the quick response.  The issue appears even in a generic created panel (see reproduction steps in original post)
For simplicity sake, here is the generic panel generated:
`panels:
  panel-1:
    perm: default
    rows: 2
    title: '&8Generated panel-1'
    command: panel-1
    empty: BLACK_STAINED_GLASS_PANE
    item:
      '0':
        material: BARREL
        name: ''
        commands:
        - cpc
      '4':
        material: STRING
        name: ''
      '7':
        material: SPIDER_EYE
        name: ''`

**Comment by fireFerry** [comment]
We did see that paper had a color code issue, and I don't think they've patched it yet so paper could be the issue too

**Comment by TheLonelyWolf1** [comment]
Hello.
I setup a completely new Paper 1.16 Testserver on my machine to look into it. 

But as much as i tried, i couldn't replicate your issue. For me it's not generating any error while generating a panel like yours.

This is weird....more investigation into that problem is needed.

**Comment by TheLonelyWolf1** [comment]
Can you check yourself whether your problem persists or not. That way we could identify if it has to do with Paper, like fireferry mentioned.

**Comment by rockyhawk64** [comment]
Using paper-68 I was unable to reproduce this, however, I have done optimizations and changes in the code for a new update that has been released (3.2.1) https://www.spigotmc.org/resources/command-panels-custom-guis.67788/update?update=346238

There are some changes in the area where the problem appeared to be coming from on your error, check with the new update and see if those have cleared any issues.

**Comment by mcdaddytalk** [comment]
Thanks guys.

I’ll try with update and also back rev paper as this didn’t seem to be happening on build 34
I can also try it on spigot to verify if it’s paper or not.

**Comment by mcdaddytalk** [comment]
Update:  CP 3.2.1 and paper 74 are good to go on this issue.
