### ISSUE TITLE
Command Panels Incompatibility w/ VotingPlugin

### ISSUE THREAD

**Issue by zombieman2020** [rockyhawk64/CommandPanels#84]
Server info:
Version: 1.16.4
Software: PaperMC
----------------------
Issue:
After I installed the plugin for my vote listener in conjunction with the votifier plugin. I first noticed that the server item that I created no longer was an existing command panel item anymore. So I dropped it and then I issued several commands that the plugin provides, and all resulted in an error saying that an Internal Error had occurred while attempting to perform the command. And then when I checked the console this error message was displaying.

Console:
[16:20:06 INFO]: zombieman2020 issued server command: /cp panel-13
[16:20:06 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cp' in plugin CommandPanels v3.13.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-267]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2007) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1818) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1771) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1265) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-267]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoClassDefFoundError: com/Ben12345rocks/VotingPlugin/UserManager/UserManager
        at me.rockyhawk.commandpanels.CommandPanels.setCpPlaceholders(CommandPanels.java:409) ~[?:?]
        at me.rockyhawk.commandpanels.CommandPanels.papi(CommandPanels.java:257) ~[?:?]
        at me.rockyhawk.commandpanels.openpanelsmanager.OpenGUI.openGui(OpenGUI.java:29) ~[?:?]
        at me.rockyhawk.commandpanels.classresources.ExecuteOpenVoids.openCommandPanel(ExecuteOpenVoids.java:77) ~[?:?]
        at me.rockyhawk.commandpanels.commands.Commandpanel.onCommand(Commandpanel.java:74) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-267]
        ... 19 more
Conclusion:
So it's apparent that there some confliction with the VotingPlugin that I recently installed after experiencing these sudden issues. If you could please help me resolve this issue I would greatly appreciate it.

**Comment by TinyTank800** [comment]
please update you cp to the latest version. any version below 3.14.0.1 will not work with voting plugin V6

**Comment by zombieman2020** [comment]
Okay thank you so much, silly me.
